In [3]:
import pandas as pd
import numpy as np
import os,sys
#from MakeOverlappingPlots import CallRun

sys.path.append('../')
from HouseKeepingFunctions import CheckFileExistence,CreateDirectory


from sklearn.model_selection import train_test_split
from sklearn.svm import OneClassSVM
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
#from sklearn.externals import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.externals import joblib
#import joblib
from collections import Counter

# TRAIN RANDOM FOREST
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
#from sklearn.externals import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
#from CreateStatsAndProgressionPlots import GenerateStatsAndProgressionPlot,GetCOPDIndex

In [9]:
IndexFilePath='/dsa/home/pg3fy/jupyter/IR/COPD/NEW_WORK_For_IE_Ratio_AND_FeatureExtraction_AND_Clustering_PythonPeakDetection/PlottingCombined/Predictions/'
Index_File=IndexFilePath+'Indexes2.csv'#WithRestlessness' Output For Notebook 


In [13]:
df=pd.DataFrame()
#print(IPathFile)
#df=pd.read_csv(Index_File,index_col=None)
df=pd.read_csv(Index_File,index_col=None)
df=df.drop(columns=['Unnamed: 0','Index','ID','Date'])

X=df.iloc[:,df.columns!='label']
y=df.label
df.head()

Ru_mDI  Ru_RespRate  Ru_RMSSD  Ru_MADI    Ru_RMI  Ru_RMDA_RMS  \
0  0.638333           15  0.830276    1.775  0.421302     1.019169   
1  0.566000           13  0.635091    1.080  0.362715     0.994024   
2  0.470000           15  0.508852    0.705  0.395330     0.997147   
3  0.348333           15  0.481612    0.940  0.402845     0.983772   
4  0.461000           14  0.499795    0.735  0.384690     1.008863   

   Restlessness3Sec  BPI_ht_Mean_max  label  
0          0.016750         0.255469      5  
1          0.050500         0.185353      5  
2          0.000000         0.232336      5  
3          0.016667         0.238651      5  
4          0.016750         0.224353      5

In [17]:
#SPLITTING DATA INTO TESTING AND TRAINING
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30, random_state=42)


In [18]:
X_val, X_final, y_val, y_final = train_test_split(X_test, y_test,test_size=0.50, random_state=42)


In [19]:

#Path='/dsa/home/pg3fy/jupyter/IR/COPD/NEW_WORK_For_IE_Ratio_AND_FeatureExtraction_AND_Clustering_PythonPeakDetection/PlottingCombined/'
#Index_File=IPath+'Indexes.csv'






#PARAMS TO BE TESTED IN GRID
param_grid = {
    'bootstrap': [True],
    'max_depth': [5,10, 20, 30, 40],
    'n_estimators': [25,50,70,100, 130, 150, 200]
}

In [20]:
#mODEL Training
Model=RandomForestClassifier()#,class_weight=class_weight)
#scores = cross_val_score(clf, X_train,y_train, cv=5)
clf2 = GridSearchCV(estimator=Model, cv=10, n_jobs=4,param_grid=param_grid,verbose=2)
clf2.fit(X_train, y_train)
print("Training Score: ",clf2.best_score_)
print(clf2.best_estimator_)

print("Statistics for testing the model with test data")
y_pred=clf2.predict(X_val)
print("Testing Score: ",accuracy_score(y_val,y_pred))
print("Confusion Matrix:===> ","\n", confusion_matrix(y_val, y_pred),"\n")
print("Classification Report:===> ","\n", classification_report(y_val, y_pred))
print("Best Accuracy Score:===> ", clf2.best_score_)

print("Labels in labelled data: ",sorted(Counter(df['label'].to_list()).items()))
#joblib.dump(clf2, 'RandomForest_birch_9.pkl')
    

Fitting 10 folds for each of 35 candidates, totalling 350 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    4.5s
[Parallel(n_jobs=4)]: Done 154 tasks      | elapsed:   19.7s
[Parallel(n_jobs=4)]: Done 350 out of 350 | elapsed:   48.7s finished


Training Score:  0.9879394405953298
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=40, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=150, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
Statistics for testing the model with test data
Testing Score:  0.9868263473053892
Confusion Matrix:===>  
 [[ 73   0   0   0   0   0]
 [  0 186   3   1   0   0]
 [  0   1 228   4   0   0]
 [  0   0   1  67   0   0]
 [  0   0   0   1 151   0]
 [  0   0   0   0   0 119]] 

Classification Report:===>  
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        73
           1       0.99      0.98      0.99       190
           2       0.98      0.98      0.98       233
           3       0.

In [22]:

y_pred=clf2.predict(X_final)
print("Testing Score: ",accuracy_score(y_final,y_pred))
print("Confusion Matrix:===> ","\n", confusion_matrix(y_final, y_pred),"\n")
print("Classification Report:===> ","\n", classification_report(y_final, y_pred))


Testing Score:  0.9856459330143541
Confusion Matrix:===>  
 [[ 87   2   0   0   0   0]
 [  0 183   2   0   0   0]
 [  0   1 234   1   0   0]
 [  0   0   1  71   0   0]
 [  0   0   0   2 137   0]
 [  0   0   0   3   0 112]] 

Classification Report:===>  
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        89
           1       0.98      0.99      0.99       185
           2       0.99      0.99      0.99       236
           3       0.92      0.99      0.95        72
           4       1.00      0.99      0.99       139
           5       1.00      0.97      0.99       115

   micro avg       0.99      0.99      0.99       836
   macro avg       0.98      0.98      0.98       836
weighted avg       0.99      0.99      0.99       836

